### ISSUE TITLE
CT a particle should be removed in one of the above cases

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#159] opened 2023-08-21 16:21 UTC
```
build-a-nucleus : interactive-description-fuzz-fuzzBoard-combo : unbuilt
http://128.138.93.172//continuous-testing/ct-snapshots/1692628527989/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692628527989%22%2C%22timestamp%22%3A1692630613231%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard
Uncaught Error: Assertion failed: a particle should be removed in one of the above cases
Error: Assertion failed: a particle should be removed in one of the above cases
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1692628527989/assert/js/assert.js:28:13)
at assert (BANScreenView.ts:768:18)
at step (Sim.ts:432:18)
at apply (PhetioAction.ts:161:16)
at execute (Sim.ts:1017:30)
at stepSimulation (Sim.ts:1007:11)
at stepOneFrame (Sim.ts:982:11)
[URL] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1692628527989%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26supportsInteractiveDescription%3Dtrue%26fuzz%26fuzzBoard&duration=40000&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692628527989%22%2C%22timestamp%22%3A1692630613231%7D
[NAVIGATED] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1692628527989%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26supportsInteractiveDescription%3Dtrue%26fuzz%26fuzzBoard&duration=40000&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692628527989%22%2C%22timestamp%22%3A1692630613231%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1692628527989/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692628527989%22%2C%22timestamp%22%3A1692630613231%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: a particle should be removed in one of the above cases
[PAGE ERROR] Error: Error: Assertion failed: a particle should be removed in one of the above cases
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1692628527989/assert/js/assert.js:28:13)
at ChartIntroScreenView.step (http://128.138.93.172//continuous-testing/ct-snapshots/1692628527989/chipper/dist/js/build-a-nucleus/js/common/view/BANScreenView.js:614:19)
at http://128.138.93.172//continuous-testing/ct-snapshots/1692628527989/chipper/dist/js/joist/js/Sim.js:353:19
at PhetioAction.execute (http://128.138.93.172//continuous-testing/ct-snapshots/1692628527989/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at Sim.stepSimulation (http://128.138.93.172//continuous-testing/ct-snapshots/1692628527989/chipper/dist/js/joist/js/Sim.js:856:31)
at Sim.stepOneFrame (http://128.138.93.172//continuous-testing/ct-snapshots/1692628527989/chipper/dist/js/joist/js/Sim.js:846:12)
at Sim.runAnimationLoop (http://128.138.93.172//continuous-testing/ct-snapshots/1692628527989/chipper/dist/js/joist/js/Sim.js:824:12)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 8/21/2023, 8:35:27 AM
```

**Comment by marlitas** [comment] 2023-08-21 16:31
@KatieWoe, @zepumph is now working with @Luisav1 on this, so he should be assigned to future issues.

**Comment by KatieWoe** [comment] 2023-08-21 16:40
Ok. Is there a way to change the responsible dev document to reflect this?

**Comment by marlitas** [comment] 2023-08-21 16:43
Hmm... that's a good question... let me check with KP and MK on that.

**Comment by zepumph** [comment] 2023-08-21 18:08
Thanks, this is a duplicate of https://github.com/phetsims/build-a-nucleus/issues/129

**Closed as completed by zepumph** 2023-08-21 18:08 UTC
Labels: type:automated-testing

**Comment by marlitas** [comment] 2023-08-21 22:47
FYI I changed the responsible dev and committed to this issue.
