### ISSUE TITLE
When spinners are enabled is incorrect in xhtml version with Win10 + FF

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#29] opened 2022-06-09 15:07 UTC
**Test device**
Dell

**Operating System**
Win10

**Browser**
Firefox

**Problem description**
For https://github.com/phetsims/qa/issues/809 with Win10 + FF + xhtml version:

When the number spinners are disabled/abled doesn't match other platforms. For example, if I increase the number of neutrons, when I reach 2, the spinners don't become disabled and I could increase the amount of neutrons to 6 without an issue. Once I reach 6 neutrons, the spinners are all disabled. On other platforms, all of the top spinners are enabled. 

I tried this with mac + FF/chrome/safari and Win10 + chrome with the xhtml version and didn't see this issue. This issue also doesn't happen with the html version of the sim with Win10 + FF. 

**Steps to reproduce**
1. In the xhtml version, increase the number of neutrons to 2--spinners are still enabled (but shouldn't be)
2. Keep increasing the number of neutrons to 6--spinners are disabled (but top spinners should be)

**Visuals**

https://user-images.githubusercontent.com/87318828/172879615-7cfd90e5-1389-45f9-ad24-6d99f17d8865.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-betaDecay.11/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-betaDecay.11 2022-06-04 01:06:50 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Language: en-US
Window: 1273x578
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Nancy-Salpepi** [comment] 2022-06-09 15:45
After clearing my history I can no longer reproduce this issue.

**Comment by Luisav1** [comment] 2022-06-15 22:38
@chrisklus and I tried out the xhtml version on my machine in Windows 10 and FF and couldn't reproduce the issue either. Closing.

**Closed as completed by Luisav1** 2022-06-15 22:38 UTC
Labels: type:bug
