### ISSUE TITLE
CT Attempt to remove particle that is not in this particle atom.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#74] opened 2023-02-08 17:57 UTC
```
build-a-nucleus : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675868372009%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught Error: Attempt to remove particle that is not in this particle atom.
Error: Attempt to remove particle that is not in this particle atom.
at ty.removeParticle (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675868372009%7D&fuzz&memoryLimit=1000:975:1627815)
at Ty.returnParticleToStack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675868372009%7D&fuzz&memoryLimit=1000:975:1666402)
at v (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675868372009%7D&fuzz&memoryLimit=1000:975:1659137)
at fm.leftArrowFill (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675868372009%7D&fuzz&memoryLimit=1000:975:1658718)
at n.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675868372009%7D&fuzz&memoryLimit=1000:975:23807)
at c.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675868372009%7D&fuzz&memoryLimit=1000:975:8174)
at li.fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675868372009%7D&fuzz&memoryLimit=1000:975:1171120)
at s (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675868372009%7D&fuzz&memoryLimit=1000:975:1170557)
at r.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675868372009%7D&fuzz&memoryLimit=1000:975:23807)
at a._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675868372009%7D&fuzz&memoryLimit=1000:975:18128)
id: Bayes Puppeteer
Snapshot from 2/8/2023, 5:01:22 AM

----------------------------------

build-a-nucleus : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675861750262%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Attempt to remove particle that is not in this particle atom.
Error: Attempt to remove particle that is not in this particle atom.
at (ParticleAtom.js:411:12)
at removeParticle (BANScreenView.ts:675:28)
at returnParticleToStack (BANScreenView.ts:283:11)
at decreaseNucleonCountListener (BANScreenView.ts:299:61)
at listener (TinyEmitter.ts:95:8)
at PHET_IO_ENABLED (Emitter.ts:121:11)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:309:22)
id: Bayes Puppeteer
Snapshot from 2/8/2023, 5:01:22 AM

----------------------------------

build-a-nucleus : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675874109928%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: No particles of particleType NEUTRON are in the particleAtom.
Error: Assertion failed: No particles of particleType NEUTRON are in the particleAtom.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/assert/js/assert.js:28:13)
at assert (BANModel.ts:120:14)
at getParticlesByType (BANModel.ts:104:43)
at getParticleToReturn (BANScreenView.ts:672:40)
at returnParticleToStack (BANScreenView.ts:285:13)
at decreaseNucleonCountListener (BANScreenView.ts:256:14)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:125:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
id: Bayes Puppeteer
Snapshot from 2/8/2023, 5:01:22 AM

----------------------------------

build-a-nucleus : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675863105849%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: No particles of particleType PROTON are in the particleAtom.
Error: Assertion failed: No particles of particleType PROTON are in the particleAtom.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/assert/js/assert.js:28:13)
at assert (BANModel.ts:120:14)
at getParticlesByType (BANModel.ts:104:43)
at getParticleToReturn (BANScreenView.ts:672:40)
at returnParticleToStack (BANScreenView.ts:283:11)
at decreaseNucleonCountListener (BANScreenView.ts:256:14)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:125:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
id: Bayes Puppeteer
Snapshot from 2/8/2023, 5:01:22 AM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675857682936/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1675857682936%22%2C%22timestamp%22%3A1675862159450%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Attempt to remove particle that is not in this particle atom.
Error: Attempt to remove particle that is not in this particle atom.
at (ParticleAtom.js:411:12)
at removeParticle (BANScreenView.ts:675:28)
at returnParticleToStack (BANScreenView.ts:283:11)
at decreaseNucleonCountListener (BANScreenView.ts:299:61)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:125:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:309:22)
id: Bayes Puppeteer
Snapshot from 2/8/2023, 5:01:22 AM
```

**Comment by veillette** [comment] 2023-02-10 16:00
Here are the steps to reproduce.

Go to chart-intro
- Add three pairs of proton-neutron with spinner
- Remove one proton with the spinner

Noticed at this point that the protons on the first shell are slightly offset.

- Remove one more proton with the spinner.

The removal of this proton triggers the assertion.

**Comment by marlitas** [comment] 2023-06-06 23:18
Here's a patch for debugging... closer to knowing the problem, not necessarily closer at getting a solution.

<details>

```diff
Subject: [PATCH] A patch that helps debug
---
Index: build-a-nucleus/js/chart-intro/model/ParticleNucleus.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build-a-nucleus/js/chart-intro/model/ParticleNucleus.ts b/build-a-nucleus/js/chart-intro/model/ParticleNucleus.ts
--- a/build-a-nucleus/js/chart-intro/model/ParticleNucleus.ts	(revision 5e8d3d281610063dcb160ddf28547da8f98301d6)
+++ b/build-a-nucleus/js/chart-intro/model/ParticleNucleus.ts	(date 1686091753013)
@@ -142,6 +142,8 @@
     assert && assert( openParticleShellPosition !== undefined, 'To add a particle there must be an empty particleShellPosition.' );
 
     openParticleShellPosition!.particle = particle;
+    console.log( 'added to shell position' );
+
     // @ts-expect-error openParticleShellPosition should never be undefined
     const viewDestination = this.modelViewTransform.modelToViewXY( openParticleShellPosition.xPosition, yPosition );
 
@@ -158,22 +160,31 @@
 
   public override removeParticle( particle: Particle ): void {
     const nucleonShellPositions = particle.type === ParticleType.PROTON.name.toLowerCase() ? this.protonShellPositions : this.neutronShellPositions;
+    const nucleonCount = particle.type === ParticleType.PROTON.name.toLowerCase() ? this.protonCountProperty.value : this.neutronCountProperty.value;
+    const shellCount = this.numberofParticlesInShell( nucleonShellPositions );
     nucleonShellPositions.forEach( nucleonShellRow => {
       nucleonShellRow.forEach( nucleonShellPosition => {
         if ( nucleonShellPosition.particle === particle ) {
+          console.log( 'remove particle from shell position' );
           nucleonShellPosition.particle = undefined;
         }
       } );
     } );
 
-    super.removeParticle( particle );
-  }
+
+    // In that case handle sending back to creator node...
+    if ( nucleonCount === shellCount ) {
+      super.removeParticle( particle );
+    }
 
+    this.reconfigureNucleus();
+  }
+
   /**
    * Fill all nucleons in open positions from bottom to top, left to right
    */
   private updateNucleonPositions( particleArray: ObservableArray<Particle>, particleShellPositions: ParticleShellPosition[][],
-                                   levelFillProperty: EnumerationProperty<EnergyLevelType>, xOffset: number ): void {
+                                  levelFillProperty: EnumerationProperty<EnergyLevelType>, xOffset: number ): void {
     const levelWidth = this.modelViewTransform.modelToViewX( ALLOWED_PARTICLE_POSITIONS[ 1 ][ 5 ] ) -
                        this.modelViewTransform.modelToViewX( ALLOWED_PARTICLE_POSITIONS[ 1 ][ 0 ] );
     particleArray.forEach( ( particle, index ) => {
@@ -220,6 +231,18 @@
       particle.inputEnabledProperty.value = inputEnabled;
     } );
   }
+
+  private numberofParticlesInShell( nucleonShellPositions: ParticleShellPosition[][] ): number {
+    let count = 0;
+    nucleonShellPositions.forEach( row => {
+      row.forEach( particleShellPosition => {
+        if ( particleShellPosition.particle !== undefined ) {
+          count++;
+        }
+      } );
+    } );
+    return count;
+  }
 }
 
 buildANucleus.register( 'ParticleNucleus', ParticleNucleus );
Index: build-a-nucleus/js/common/view/BANScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build-a-nucleus/js/common/view/BANScreenView.ts b/build-a-nucleus/js/common/view/BANScreenView.ts
--- a/build-a-nucleus/js/common/view/BANScreenView.ts	(revision 5e8d3d281610063dcb160ddf28547da8f98301d6)
+++ b/build-a-nucleus/js/common/view/BANScreenView.ts	(date 1686092955513)
@@ -492,6 +492,7 @@
 
     // place the particle the center of the particleAtom and add it to the model and particleAtom
     particle.setPositionAndDestination( this.model.particleAtom.positionProperty.value );
+    console.log( 'Position and destination immediately set' );
     this.model.addParticle( particle );
     this.model.particleAtom.addParticle( particle );
   }
@@ -522,6 +523,7 @@
 
     // send the particle the center of the particleAtom and add it to the model
     particle.destinationProperty.value = this.model.getParticleDestination( particleType, particle );
+
     this.model.addParticle( particle );
 
     // don't let the particle be clicked until it reaches the particleAtom
@@ -537,7 +539,7 @@
 
     // add the particle to the particleAtom once it reaches the center of the particleAtom and allow it to be clicked
     particle.animationEndedEmitter.addListener( () => {
-      if ( !this.model.particleAtom.containsParticle( particle ) ) {
+      if ( !this.model.particleAtom.containsParticle( particle ) && particle.positionProperty.value === particle.destinationProperty.value ) {
 
         // must remove incoming particles before adding it to particleAtom so incoming count is accurate
         if ( particleType === ParticleType.PROTON ) {
@@ -547,6 +549,7 @@
           arrayRemove( this.model.incomingNeutrons, particle );
         }
 
+        // TODO: We add the particle to the particleAtom, even if we interrupted it's animation and changed it's destination property.
         this.model.particleAtom.addParticle( particle );
         particleView.inputEnabled = true;
         particle.animationEndedEmitter.removeAllListeners();
Index: shred/js/model/Particle.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/shred/js/model/Particle.js b/shred/js/model/Particle.js
--- a/shred/js/model/Particle.js	(revision 555d948bc313b6503740abc35b3334f683448730)
+++ b/shred/js/model/Particle.js	(date 1686093050813)
@@ -76,6 +76,8 @@
       tandem: options.tandem && options.tandem.createTandem( 'destinationProperty' )
     } );
 
+    this.destinationProperty.link( destination => this.animationEndedEmitter.removeAllListeners() );
+
     // @public
     this.radiusProperty = new NumberProperty(
       type === 'electron' || type === 'positron' ? ShredConstants.ELECTRON_RADIUS : ShredConstants.NUCLEON_RADIUS,
Index: shred/js/model/ParticleAtom.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/shred/js/model/ParticleAtom.js b/shred/js/model/ParticleAtom.js
--- a/shred/js/model/ParticleAtom.js	(revision 555d948bc313b6503740abc35b3334f683448730)
+++ b/shred/js/model/ParticleAtom.js	(date 1686091502344)
@@ -299,6 +299,7 @@
 
       // Add the particle and update the counts.
       const particleArray = particle.type === 'proton' ? this.protons : this.neutrons;
+      console.log( 'particle added to array' );
       particleArray.push( particle );
       this.reconfigureNucleus();
     }
@@ -358,7 +359,7 @@
    * @public
    */
   removeParticle( particle ) {
-
+    console.log( 'remove the particle from particle atom' );
     if ( this.protons.includes( particle ) ) {
       this.protons.remove( particle );
     }
```
</details>

**Comment by marlitas** [comment] 2023-06-16 15:42
Past issues that may be helpful in discovery:
- https://github.com/phetsims/build-a-nucleus/issues/18
- https://github.com/phetsims/build-a-nucleus/issues/62

**Comment by zepumph** [comment] 2023-07-10 19:37
I believe I handled this in a way that is ready for review. Instead of making the model supportive of this case, I tried out changing the enabledProperty logic of the buttons. If there are only animating atoms, but not actually any to decrease, then don't say those buttons are enabled.

@Luisav1 will you please review? I'll check back in on CT later today.

**Comment by marlitas** [comment] 2023-07-10 19:49
I love the brilliance of this but I think it only handles the base-case of the problem... 

https://github.com/phetsims/build-a-nucleus/assets/42476338/fb9e5807-4526-4f34-a62c-536710834832

The buttons will still attempt to remove the last created particle even if it hasn't reached the atom yet... 😢

**Comment by zepumph** [comment] 2023-07-27 22:40
I reverted https://github.com/phetsims/build-a-nucleus/commit/6c5c3991574209632a497f06742669d96016bc54 in https://github.com/phetsims/build-a-nucleus/commit/b642311347c99cc84c8fe8494bb7ac39cc538031 because it seemed poorly thought out and too limited in scope (see https://github.com/phetsims/build-a-nucleus/issues/74#issuecomment-1629628501), but when I did, I started getting this error on CT all over the place:

```
Error: Assertion failed: No particles of particleType NEUTRON are in the particleAtom.
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1690495493761/assert/js/assert.js:28:13)
at assert (BANModel.ts:121:14)
at getParticlesByType (BANModel.ts:105:43)
at getParticleToReturn (BANScreenView.ts:608:40)
at returnParticleToStack (BANScreenView.ts:286:13)
at decreaseNucleonCountListener (BANScreenView.ts:257:14)
at listener (TinyEmitter.ts:122:8)
at emit (Emitter.ts:61:21)
at emit (PushButtonModel.ts:179:22)
```

So I will bring it back in https://github.com/phetsims/build-a-nucleus/commit/ba953c547b18fe1ed8c4b478a89c93c8e1874413 for now.

Also, in https://github.com/phetsims/build-a-nucleus/commit/4596d78aa47c8b83e1ef80892db8f468f053d258 @Luisav1 and I were finally able to crack the "item not found in array" bug by keeping the shell positions in sync in the case where you return a particle that is animating towards the atom, but hasn't made it yet. We will keep cracking at CT errors, and will likely clean up some issues quite soon.

**Comment by zepumph** [comment] 2023-07-28 16:41
I am a bit confused why we ended up needing the validation for empty particleAtom, but I can see it as a good workaround. It seems better to handle this in the view, than to try to make all of the "extract particle" logic be graceful to if there is no particle of that type in the particleAtom. https://github.com/phetsims/build-a-nucleus/commit/ba953c547b18fe1ed8c4b478a89c93c8e1874413 is here to stay (or at least that is what CT has to say. I would like to close this issue, but I think it would be useful to just have @Luisav1 take a look at https://github.com/phetsims/build-a-nucleus/blob/2943a451fba7d36fdf48e89ec6b5f1215b0013db/js/common/view/BANScreenView.ts#L236-L242 and make sure that she doesn't recommend any other changes.

**Comment by Luisav1** [comment] 2023-08-01 20:19
I wouldn't recommend any other changes, that is looking good to me! Closing.

**Closed as completed by Luisav1** 2023-08-01 20:19 UTC
Labels: status:ready-for-review
