### ISSUE TITLE
Some nuclides are hard to get

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#21] opened 2022-06-07 21:49 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/809
If a nuclide "does not form" then the inputs are disabled and the nuclide reverts to something that does form. However, there are nuclides on the spreadsheet of things the sim will show that are are separated from their neighbor. This means that if you try to add neutrons to get to a nuclide, you may hit one that can't be formed and be prevented from easily reaching the target. An example is that C-20 and C-22 can form, but C-21 can't making it hard to get to C-22. You can form it by getting more creative and coming at it from another element, but a student exploring probably won't find it, they'd need to know what to look for and it would still be hard. In addition, if you are on C-22, you are prevented from removing a neutron at all to get to more standard carbon forms.

This problem happens for other elements as well, and, though I haven't found them, may make some nuclides impossible to create.

In general, I found the disabling of the controls when passing through something that wouldn't form made it frustrating to make nuclides in general. This design decision may need to be revisited.

**Steps to reproduce**
1. Create carbon-12 with the button to add a proton and a neutron.
2. Keep adding neutrons until you get C-20
3. Add another neutron and note that you can't add a second
4. Add two sets of proton+neutrons to get O-24
5. Take away two protons to get C-22 and see that it is valid, but you can't remove a neutron
6. This may be easier to see/recreate with the fact that you can have 1, 4, or 6 neutrons with no protons, but nothing in between

**Visuals**
![hardtoget](https://user-images.githubusercontent.com/41024075/172488558-c82a2996-41c8-48c6-a36a-41ae6e92d1f6.gif)
![hardtoget2](https://user-images.githubusercontent.com/41024075/172488563-544d413e-69d9-4669-9498-412d591d05f7.gif)
<img width="958" alt="cantgodown" src="https://user-images.githubusercontent.com/41024075/172488583-bbb80b44-1d53-48cc-82cd-13c5436252a7.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-betaDecay.11/phet/build-a-nucleus_all_phet.html
Version: 1.0.0-betaDecay.11 2022-06-04 01:06:50 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment] 2022-06-07 21:55
Some of the higher weight elements can also be non-obvious to create. The lightest Uranium nuclide allowed is 92 protons and 122 neutrons, so you can't get just by pressing the button to add a set of a proton and neutron over and over.

**Comment by Nancy-Salpepi** [comment] 2022-06-10 16:39
> In general, I found the disabling of the controls when passing through something that wouldn't form made it frustrating to make nuclides in general. 

I agree with @KatieWoe's comment. I felt like I should be able to move past those nuclides when holding down a control.

**Comment by ariel-phet** [comment] 2022-06-13 16:31
@Nancy-Salpepi @KatieWoe I think wee see that "frustration" in essence as a design feature and not a bug.

Nuclear stability is odd, in that although there are trends, there are not really hard and fast rules, and many nuclides *are* in fact very difficult to "get to" (form) and that helps explain their natural abundance. To get certain nuclides you need to follow a fairly complex decay path. So it is OK that certain nuclides will be difficult or near impossible to reach. Eventually, when the third screen shows the entire full chart, the user will be able to see why certain nuclides are odd ducks.

**Comment by ariel-phet** [comment] 2022-06-13 16:33
@KatieWoe @Nancy-Salpepi if you are Ok with the rationale of the above comment, let me know, and we can either close this issue, defer it to see how the sim does interviews or "in the wild" as a prototype, or bring it up at design meeting.

**Comment by KatieWoe** [comment] 2022-06-13 16:34
I'm alright with it for the most part, but think it would be good to keep an eye out in interviews to see how students react/learn.

**Comment by Nancy-Salpepi** [comment] 2022-06-13 17:16
@ariel-phet I totally understand that some nuclides are difficult to get. I just didn't like the disabling of controls aspect whenever I reached a nuclide that didn't form. I am totally fine with deferring until interviews/prototype feedback occurs.

**Comment by KatieWoe** [comment] 2022-08-04 20:15
Secondary note, some also seem to be impossible to get.

**Comment by zepumph** [comment] 2023-07-21 16:27
@Luisav1, can you please note what the next steps are for this issue. I'm not sure what we discussed when triaging last week.

**Comment by Luisav1** [comment] 2023-07-28 17:14
@zepumph We decided that the next steps for this would be to see how interviews go and if there are any issues in getting to certain nuclides.

**Comment by zepumph** [comment] 2023-08-17 18:09
@arouinfar @Luisav1, it sounded like nothing of note came out of interviews in terms of learners having a hard time with nuclides that are challenging to get to. Let's go ahead and close this issue as a wontfix.

**Closed as completed by zepumph** 2023-08-17 18:09 UTC
Labels: type:wontfix, design:interviews, type:suggestion
