### ISSUE TITLE
Can we retain any sort of asset file for the `fullNuclideChart.png` image?

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-a-nucleus#180] opened 2023-08-24 19:23 UTC
From code review, see #165.

There is an item in the code review checklist that says, "Is there a file in assets/ for every resource file in sound/ and images/?"  There isn't such an asset file for `fullNuclideChart.png`, but this may well be a case where it isn't possible to have one.  @Luisav1 - The license file entry for this image says, "unmodified screenshot of project created by Luisa Vargas".  Is there any other sort of asset that we should retain if we ever wanted to, so, produce a higher-res version of this image?  If not, can you enhance the note to say how it could be recreated if necessary?

**Comment by zepumph** [comment] 2023-08-28 16:10
While looking over this, I made a small refactor with the full chart push button. I also updated the notes. I'm not sure how the background became white, for reproducibility, it may be nice to note that @Luisav1. Can you finish this one off?

**Comment by zepumph** [comment] 2023-08-28 17:49
On hold until https://github.com/phetsims/build-a-nucleus/issues/168 is ready.

**Comment by Luisav1** [comment] 2023-09-15 19:03
Talking with @zepumph, taking this off-hold since we only need to update the license to match necessary steps to have the current screenshot (even though the link's chart colors would eventually match).

**Comment by Luisav1** [comment] 2023-09-18 15:32
Updated license.json to include details to get current screenshot. Closing.

**Closed as completed by Luisav1** 2023-09-18 15:32 UTC
Labels: dev:code-review, status:ready-for-review
